---
title: "Untitled"
author: "jingwen"
date: "2018年7月17日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

---
title: "Untitled"
author: "jingwen"
date: "2018年7月15日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

model 1: 2011-2017 
```{r}
rm(list = ls())
library(readr)
library(openxlsx)
library(plyr)
library(dplyr)
library(Synth)
library(ggplot2)
library(graphics)
library(reshape2)
Product = c("Groundnut","Arhar (Tur-Red Gram)","Cotton","Green Gram (Moong)","Arecanut(Betelnut-Supari)","Bengal Gram(Gram)","Black Gram (Urd Beans)","Dry Chillies","Jowar(Sorghum)","Maize","Paddy(Dhan)")
Model = c("10-17 quarter","11-17 quarter","12-17 quarter","10-17 half year","11-17 half year","12-17 half year","10-17 year","11-17 year","12-17 year")
Begin = c(2010,2011,2012,2010,2011,2012,2010,2011,2012)
Over = c(2017,2017,2017,2017,2017,2017,2017,2017,2017)
Br = c("month","3 months","3 months","3 months","3 months","3 months","3 months","3 months","3 months")



intervention= as.data.frame(read.xlsx("E:/Dropbox/jingwen_tasks/infrastructure_characteristics/Market Details.xlsx",sheet = "Market Live Dates"))[3:160,]
intervented = tolower(as.character(intervention$X3))
intervention$X3 = tolower(intervention$X3)



  product = "Groundnut"
  


  for (m in 1:1){
    setwd("E:/Dropbox/jingwen_tasks/plots for monthly prices after wpi groundnut")
dat = c()
for (i in Begin[m]:Over[m]){
  filename = paste("E:/Dropbox/jingwen_tasks/Organized Data/",i,"_Data/",product,".xlsx",sep = "")
  print(i)
  mydf <- read.xlsx(filename, sheet = 1, startRow = 1, colNames = F)
  marketrow = (1:nrow(mydf))[!is.na(mydf$X1)]
  concluderow = (1:nrow(mydf))[is.na(mydf$X2)]
  for (j in 1:(length(marketrow)-1)){
    mydf[(marketrow[j]+1):(marketrow[j+1]-2),"X1"] = mydf[marketrow[j],"X1"]
  }
  mydf[(marketrow[length(marketrow)]+1):(nrow(mydf)-1),"X1"] = mydf[marketrow[length(marketrow)],"X1"]
  mydf = mydf[-c(marketrow,concluderow),]
  mydf$X3 = as.numeric(mydf$X3)
  for (j in 5:7){
    mydf[,j] = as.numeric(as.character(mydf[,j]))
    temp = mean(mydf[,j],na.rm = T)
    mydf[,j][is.na(mydf[,j])]=temp
  }
  dat = rbind(dat,mydf)
}

dat = dat[,c(1,2,5,6,7)]
colnames(dat) = c("market","date","min","max","modal")

dat$market = tolower(dat$market)

dat$min = as.numeric(dat$min)
dat$max = as.numeric(dat$max)
dat$modal = as.numeric(dat$modal)

dat = dat[dat$market%in%intervented,]

dat = na.omit(dat)
dat = dat[as.Date(dat$date,format = "%d/%m/%Y")<as.Date("2017/04/01"),]



wpi1 = read.xlsx("E:/Dropbox/jingwen_tasks/infrastructure_characteristics/month2till2012.xlsx",sheet = 1)
wpi1 = wpi1[wpi1$COMM_NAME == "Groundnut Seed",][,64:99]
wpi2 = read.xlsx("E:/Dropbox/jingwen_tasks/infrastructure_characteristics/monthly_wholesale_price_index_2013_17.xlsx",sheet = 1)
wpi2 = wpi2[wpi2$COMM_NAME == "Groundnut Seed",][,-(1:3)]
wpi = cbind(wpi1,wpi2)
wpimonth = seq(as.Date("2010/01/01"), as.Date("2017/03/01"), by = "month")
WPI = data.frame(month = wpimonth,wpi = as.numeric(wpi))


market = unique(dat$market)


plot_list = list()
for (i in 1:length(market)){
  try({
      subdat = data.frame(modal = dat[dat$market==as.character(market[i]),"modal"],minp = dat[dat$market==as.character(market[i]),"min"],maxp = dat[dat$market==as.character(market[i]),"max"],date = dat[dat$market==as.character(market[i]),"date"])
  subdat$minp[subdat$minp<quantile(subdat$minp,probs = c(0.01,0.99))[1]|subdat$minp>quantile(subdat$minp,probs = c(0.01,0.99))[2]] = NA
  subdat$modal[subdat$modal<quantile(subdat$modal,probs = c(0.01,0.99))[1]|subdat$modal>quantile(subdat$modal,probs = c(0.01,0.99))[2]] = NA
  subdat$maxp[subdat$maxp<quantile(subdat$maxp,probs = c(0.01,0.99))[1]|subdat$maxp>quantile(subdat$maxp,probs = c(0.01,0.99))[2]] = NA
  subdat = na.omit(subdat)
  subdat$date <- as.Date(subdat$date,
                         "%d/%m/%Y")
  subdat$month <- as.Date(cut(subdat$date,
                             breaks = "month"))
  subdat = subdat[order(as.Date(subdat$date, format="%d/%m/%Y")),]
  subintervention = as.Date(as.numeric(as.character(intervention[as.character(intervention$X3)==as.character(market[i]),"X4"]))-25569,origin = "1970-01-01")
  modal = as.data.frame(aggregate(subdat$modal, list(subdat$month), mean))
  minp = as.data.frame(aggregate(subdat$minp, list(subdat$month), mean))
  maxp = as.data.frame(aggregate(subdat$maxp, list(subdat$month), mean))
  library(plyr)
  d = join(minp,modal,by = "Group.1")
  d = join(d,maxp,by=  "Group.1")
  colnames(d) = c("month","min","modal","max")
  d = join(d,WPI,by = "month")
  d$min = (d$min*100)/d$wpi
  d$modal = (d$modal*100)/d$wpi
  d$max = (d$max*100)/d$wpi
  d = d[,-5]
  
  d2 = melt(d,id = "month")
  p = ggplot(d2, aes(month, value, colour=variable)) + 
    geom_line() +
    scale_colour_manual(values=c("red", "black","blue"))+
    scale_x_date(date_breaks = "12 months", date_labels = "%Y-%m-%d")+
    geom_vline(xintercept = subintervention)
  plot_list[[i]] = p
  print(i)
  })

}

for (i in 1:length(plot_list)) {
  try({
    file_name = paste("monthly price for ",as.character(market[i],".pdf"))
  pdf(file_name,8,4)
  print(plot_list[[i]])
  dev.off()
  })
  
}



}
```


